var brand ="mala practica";
 let counter= 100;  
 const token= "abc123";

 console.log(token);
 counter=200
 console.log(counter);

 // comentario de una linea

 /*
 es es un comentario 
 multilinea
 */

 // interpolacion

 let interpolacion =  ` el valor de counter es ${counter}`;
 console.log(interpolacion);
 console.log("el valor de counter es: ", counter);
 console.log("el valor de counter es: "+ counter);

 const personas = [
    [{
        "first_name": "Basilio",
        "last_name": "Bigg",
        "age": 64
      }, {
        "first_name": "Levin",
        "last_name": "Gaddie",
        "age": 52
      }, {
        "first_name": "Charlton",
        "last_name": "Woolaghan",
        "age": 41
      }, {
        "first_name": "Sibyl",
        "last_name": "Surr",
        "age": 77
      }, {
        "first_name": "Sheila",
        "last_name": "Cobon",
        "age": 22
      }, {
        "first_name": "Elsa",
        "last_name": "Whitfield",
        "age": 26
      }, {
        "first_name": "Gayelord",
        "last_name": "Greste",
        "age": 58
      }, {
        "first_name": "Wini",
        "last_name": "Douglass",
        "age": 55
      }, {
        "first_name": "Orel",
        "last_name": "Bew",
        "age": 49
      }, {
        "first_name": "Eugenia",
        "last_name": "McSporrin",
        "age": 25
      }, {
        "first_name": "Woodie",
        "last_name": "Swetman",
        "age": 37
      }, {
        "first_name": "Jamal",
        "last_name": "Blonden",
        "age": 43
      }, {
        "first_name": "Rory",
        "last_name": "Eason",
        "age": 79
      }, {
        "first_name": "Germain",
        "last_name": "Hartop",
        "age": 56
      }, {
        "first_name": "Shani",
        "last_name": "Izhakov",
        "age": 41
      }, {
        "first_name": "Sharlene",
        "last_name": "Dyball",
        "age": 39
      }, {
        "first_name": "Kylynn",
        "last_name": "Viollet",
        "age": 45
      }, {
        "first_name": "Kris",
        "last_name": "Bulpitt",
        "age": 35
      }, {
        "first_name": "Olive",
        "last_name": "Gaywood",
        "age": 47
      }, {
        "first_name": "Fields",
        "last_name": "Stoke",
        "age": 74
      }, {
        "first_name": "Ondrea",
        "last_name": "Poure",
        "age": 40
      }, {
        "first_name": "Mordecai",
        "last_name": "Mangin",
        "age": 30
      }, {
        "first_name": "Brigit",
        "last_name": "Pregal",
        "age": 39
      }, {
        "first_name": "Yetta",
        "last_name": "Belleny",
        "age": 65
      }, {
        "first_name": "Caz",
        "last_name": "Sabine",
        "age": 52
      }, {
        "first_name": "Abbott",
        "last_name": "Hussey",
        "age": 42
      }, {
        "first_name": "Levi",
        "last_name": "Tregear",
        "age": 42
      }, {
        "first_name": "Penny",
        "last_name": "Hobbing",
        "age": 34
      }, {
        "first_name": "Jenny",
        "last_name": "Justham",
        "age": 65
      }, {
        "first_name": "Caroline",
        "last_name": "Boom",
        "age": 52
      }, {
        "first_name": "Guinevere",
        "last_name": "Crammy",
        "age": 26
      }, {
        "first_name": "Cthrine",
        "last_name": "Degenhardt",
        "age": 46
      }, {
        "first_name": "Nana",
        "last_name": "Yegorchenkov",
        "age": 35
      }, {
        "first_name": "Boyce",
        "last_name": "Anespie",
        "age": 60
      }, {
        "first_name": "Ninette",
        "last_name": "Firks",
        "age": 35
      }, {
        "first_name": "Betsey",
        "last_name": "Terrey",
        "age": 56
      }, {
        "first_name": "Pauletta",
        "last_name": "Brimner",
        "age": 51
      }, {
        "first_name": "Elliot",
        "last_name": "Roser",
        "age": 45
      }, {
        "first_name": "Terry",
        "last_name": "Maundrell",
        "age": 48
      }, {
        "first_name": "Linda",
        "last_name": "Crepin",
        "age": 46
      }, {
        "first_name": "Damiano",
        "last_name": "Burditt",
        "age": 24
      }, {
        "first_name": "Dido",
        "last_name": "Boick",
        "age": 38
      }, {
        "first_name": "Monika",
        "last_name": "Amsberger",
        "age": 32
      }, {
        "first_name": "Annora",
        "last_name": "Harroway",
        "age": 71
      }, {
        "first_name": "Dulci",
        "last_name": "Piccard",
        "age": 30
      }, {
        "first_name": "Delphine",
        "last_name": "Watton",
        "age": 62
      }, {
        "first_name": "Claribel",
        "last_name": "Andrysiak",
        "age": 25
      }, {
        "first_name": "Mallory",
        "last_name": "Nimmo",
        "age": 21
      }, {
        "first_name": "Cord",
        "last_name": "Artus",
        "age": 33
      }, {
        "first_name": "Honey",
        "last_name": "Mendenhall",
        "age": 73
      }, {
        "first_name": "Julianna",
        "last_name": "Pashenkov",
        "age": 20
      }, {
        "first_name": "Noemi",
        "last_name": "Dadd",
        "age": 38
      }, {
        "first_name": "Josepha",
        "last_name": "Hudspeth",
        "age": 49
      }, {
        "first_name": "Clint",
        "last_name": "Arnet",
        "age": 56
      }, {
        "first_name": "Melessa",
        "last_name": "Collet",
        "age": 52
      }, {
        "first_name": "Flinn",
        "last_name": "Albone",
        "age": 30
      }, {
        "first_name": "Farrel",
        "last_name": "Drewell",
        "age": 19
      }, {
        "first_name": "Misti",
        "last_name": "Gentil",
        "age": 46
      }, {
        "first_name": "Jo-anne",
        "last_name": "Armiger",
        "age": 35
      }, {
        "first_name": "Pooh",
        "last_name": "Pyser",
        "age": 19
      }, {
        "first_name": "Abie",
        "last_name": "Hustler",
        "age": 34
      }, {
        "first_name": "Fancy",
        "last_name": "Hacquoil",
        "age": 58
      }, {
        "first_name": "Land",
        "last_name": "Marfield",
        "age": 50
      }, {
        "first_name": "Sal",
        "last_name": "Balstone",
        "age": 40
      }, {
        "first_name": "Leora",
        "last_name": "Melloy",
        "age": 22
      }, {
        "first_name": "Katrine",
        "last_name": "Gobel",
        "age": 74
      }, {
        "first_name": "Normand",
        "last_name": "Attridge",
        "age": 21
      }, {
        "first_name": "Hansiain",
        "last_name": "Gerauld",
        "age": 79
      }, {
        "first_name": "Reed",
        "last_name": "Elphinston",
        "age": 79
      }, {
        "first_name": "Jere",
        "last_name": "Allder",
        "age": 44
      }, {
        "first_name": "Rayna",
        "last_name": "Tyt",
        "age": 43
      }, {
        "first_name": "Simeon",
        "last_name": "Lorryman",
        "age": 64
      }, {
        "first_name": "Sharleen",
        "last_name": "Ventum",
        "age": 77
      }, {
        "first_name": "Rachelle",
        "last_name": "Scrowton",
        "age": 79
      }, {
        "first_name": "Renate",
        "last_name": "Szymon",
        "age": 44
      }, {
        "first_name": "Nealon",
        "last_name": "Waldera",
        "age": 64
      }, {
        "first_name": "Sharron",
        "last_name": "Blench",
        "age": 76
      }, {
        "first_name": "Esta",
        "last_name": "Gantlett",
        "age": 25
      }, {
        "first_name": "Brit",
        "last_name": "Offener",
        "age": 49
      }, {
        "first_name": "Tristan",
        "last_name": "Mantione",
        "age": 74
      }, {
        "first_name": "Tabby",
        "last_name": "Rampley",
        "age": 22
      }, {
        "first_name": "Eugen",
        "last_name": "Levick",
        "age": 71
      }, {
        "first_name": "Emory",
        "last_name": "Bonnier",
        "age": 70
      }, {
        "first_name": "Rafaellle",
        "last_name": "Budgen",
        "age": 47
      }, {
        "first_name": "Mame",
        "last_name": "Proctor",
        "age": 75
      }, {
        "first_name": "Ethyl",
        "last_name": "Muxworthy",
        "age": 67
      }, {
        "first_name": "Papagena",
        "last_name": "Vaune",
        "age": 47
      }, {
        "first_name": "Shayne",
        "last_name": "Pithcock",
        "age": 70
      }, {
        "first_name": "Eba",
        "last_name": "MacRinn",
        "age": 49
      }, {
        "first_name": "Noll",
        "last_name": "McRoberts",
        "age": 79
      }, {
        "first_name": "Lockwood",
        "last_name": "Malden",
        "age": 76
      }, {
        "first_name": "Nicol",
        "last_name": "Gee",
        "age": 43
      }, {
        "first_name": "Kevan",
        "last_name": "McRae",
        "age": 56
      }, {
        "first_name": "Darrick",
        "last_name": "Gibbon",
        "age": 59
      }, {
        "first_name": "Nonnah",
        "last_name": "Fiorentino",
        "age": 72
      }, {
        "first_name": "Tildy",
        "last_name": "Wrightam",
        "age": 60
      }, {
        "first_name": "Janeczka",
        "last_name": "D'Agostini",
        "age": 34
      }, {
        "first_name": "Isadora",
        "last_name": "Capsey",
        "age": 68
      }, {
        "first_name": "Goldia",
        "last_name": "Lambart",
        "age": 76
      }, {
        "first_name": "Joyce",
        "last_name": "Bolitho",
        "age": 46
      }]
    ];
    

      console.table(personas);
      
 